#!/usr/bin/env ruby

require 'rake'

def Plugin(github)
  user, dir = github.split('/',2)
  url = ['git://github.com/',github,'.git'].join('')

  dest = "bundle/#{dir}"
  if File.exists?(dest)
    puts "Updating #{github} ..."
    `(cd #{dest}; git pull)`
  end
  unless File.exist?(dest)
    puts "Cloning #{github} ..."
    `git clone #{url} #{dest}`
  end
end

task :default => :sync

desc "Clone those that don't exist, update those that do."
task :sync do

  # Editing
  Plugin 'tpope/vim-fugitive'
  Plugin 'mileszs/ack.vim'
  Plugin 'tpope/vim-endwise'
  Plugin 'tpope/vim-surround'
  Plugin 'tpope/vim-abolish'
  Plugin 'godlygeek/tabular'
  Plugin 'kien/rainbow_parentheses.vim'
  Plugin 'tomtom/tcomment_vim'
  Plugin 'Lokaltog/vim-easymotion'
  Plugin 'honza/vim-snippets'

  # Lang
  Plugin 'klen/python-mode'
  Plugin 'vim-ruby/vim-ruby'
  Plugin 'jnwhiteh/vim-golang'

  # Syntax
  Plugin 'scrooloose/syntastic'
  Plugin 'rodjek/vim-puppet'
  Plugin 'hdima/python-syntax'
  Plugin 'elzr/vim-json'
  Plugin 'tpope/vim-markdown'
  Plugin 'tpope/vim-git'

  Plugin 'jamessan/vim-gnupg'
  Plugin 'bling/vim-airline'
  Plugin 'clones/vim-fuzzyfinder'
  Plugin 'vim-scripts/L9'

  # Some color
  Plugin 'tomasr/molokai'
  Plugin 'noahfrederick/vim-noctu'
  Plugin 'jnurmine/Zenburn'
  Plugin 'chase/focuspoint-vim'

end

