mod 'bjoernalbers/homebrew', '0.2.0'
mod 'wfarr/osx_defaults', '0.1.2'
mod 'ssh_keygen', :git => 'git://github.com/maestrodev/puppet-ssh_keygen.git', :ref => 'v1.2.0'

#mod 'tunnelblick', :git => 'git://github.com/boxen/puppet-tunnelblick.git'

